version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "automation"
    versioning-strategy: auto
    commit-message:
      prefix: "npm"
      include: "scope" 